
Options in effect for /Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/cncKWLexer.gi:

    ACTION-BLOCK=("/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexer.java","/.","./")

    AST-DIRECTORY="./Ast"  AST-TYPE="Ast"  NOATTRIBUTES  NOAUTOMATIC-AST  
    NOBACKTRACK  BYTE  CONFLICTS  
    DAT-DIRECTORY="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/"  
    DAT-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexerdcl.data"
    
    DCL-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexerdcl.java"
    NODEBUG  
    DEF-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexerdef.java"
    DIRECTORY-PREFIX=""  NOEDIT  NOERROR-MAPS  ESCAPE='$'  
    EXPORT-TERMINALS=("/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncParsersym.java","TK_","")
    EXTENDS-PARSETABLE  FACTORY="new "  FILE-PREFIX="CncKWLexer"  NOFIRST  
    NOFOLLOW  NOGLR  NOGOTO-DEFAULT  
    GRM-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/cncKWLexer.gi"
    
    IMP-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexerimp.java"
    
    INCLUDE-DIRECTORY="/Users/alina/Documents/workspace/lpg.generator/templates/java;/Users/alina/Documents/workspace/lpg.generator/include/java;"
    LALR=1  LEGACY  NOLIST  MARGIN=4  MAX-CASES=1024  NAMES=OPTIMIZED  
    NONT-CHECK  OR_MARKER='|'  
    OUT-DIRECTORY="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/"  
    PACKAGE="CnCParser"  NOPARENT-SAVE  
    PARSETABLE-INTERFACES="lpg.runtime.ParseTable"  PREFIX="Char_"  PRIORITY  
    PROGRAMMING_LANGUAGE=JAVA  
    PRS-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexerprs.java"
    NOQUIET  READ-REDUCE  REMAP-TERMINALS  RULE_CLASSNAMES=SEQUENTIAL  NOSCOPES
    NOSERIALIZE  NOSHIFT-DEFAULT  SINGLE-PRODUCTIONS  NOSOFT-KEYWORDS  NOSTATES
    SUFFIX=""  
    SYM-FILE="/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/CncKWLexersym.java"
    TAB-FILE="cncKWLexer.t"  TABLE  TEMPLATE="KeywordTemplateF.gi"  
    TRACE=CONFLICTS  NOVARIABLES  NOVERBOSE  NOVISITOR  VISITOR-TYPE="Visitor"
    WARNINGS  NOXREF  

/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:19:24:19:24:492:492: Warning: The macro "$" is undefined. No substitution made
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:2:5:2:14:16:25: Informative: The terminal DollarSign is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:3:5:3:11:39:45: Informative: The terminal Percent is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:4:5:4:5:59:59: Informative: The terminal _ is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:5:5:5:65:65: Informative: The terminal a is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:7:5:7:67:67: Informative: The terminal b is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:15:5:15:75:75: Informative: The terminal f is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:19:5:19:79:79: Informative: The terminal h is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:23:5:23:83:83: Informative: The terminal j is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:25:5:25:85:85: Informative: The terminal k is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:27:5:27:87:87: Informative: The terminal l is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:29:5:29:89:89: Informative: The terminal m is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:33:5:33:93:93: Informative: The terminal o is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:35:5:35:95:95: Informative: The terminal p is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:37:5:37:97:97: Informative: The terminal q is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:49:5:49:109:109: Informative: The terminal w is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:51:5:51:111:111: Informative: The terminal x is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:53:5:53:113:113: Informative: The terminal y is useless.
/Users/alina/Documents/workspace/lpg.generator/include/java/KWLexerFoldedCaseMapF.gi:5:55:5:55:115:115: Informative: The terminal z is useless.


/Users/alina/Rice/CnC-C/trunk/CnCLPGParser/src/CnCParser/cncKWLexer.gi:34:5:34:11:461:467: Informative: Grammar is  LR(0).

Number of Terminals: 30
Number of Nonterminals: 1
Number of Productions: 4
Number of Single Productions: 0
Number of Items: 22
Number of States: 16
Number of Shift actions: 14
Number of Goto actions: 1
Number of Shift/Reduce actions: 3
Number of Goto/Reduce actions: 0
Number of Reduce actions: 1
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0

Number of entries in base Action Table: 17
Additional space required for compaction of Action Table: 5.8%

Number of unique terminal states: 16
Number of Shift actions saved by merging: 0
Number of Conflict points saved by merging: 0
Number of Reduce actions saved by merging: 0
Number of Reduce saved by default: 0

Number of entries in Terminal Action Table: 34
Additional space required for compaction of Terminal Table: 20.5%

Actions in Compressed Tables:
     Number of Shifts: 14
     Number of Shift/Reduces: 3
     Number of Gotos: 1
     Number of Goto/Reduces: 0
     Number of Reduces: 1
     Number of Defaults: 0

Parsing Tables storage:
    Storage required for BASE_CHECK: 4 Bytes
    Storage required for BASE_ACTION: 23 Bytes
    Storage required for TERM_CHECK: 65 Bytes
    Storage required for TERM_ACTION: 42 Bytes
