
//
// This file is part of the CNC-C implementation and
// distributed under the Modified BSD License. 
// See LICENSE for details.
// 
// I AM A GENERATED FILE. PLEASE DO NOT CHANGE ME!!!
//

package CnCParser;

public interface CncLexersym {
    public final static int
      Char_CtlCharNotWS = 102,
      Char_LF = 75,
      Char_CR = 76,
      Char_HT = 11,
      Char_FF = 12,
      Char_a = 13,
      Char_b = 14,
      Char_c = 15,
      Char_d = 16,
      Char_e = 17,
      Char_f = 18,
      Char_g = 19,
      Char_h = 20,
      Char_i = 21,
      Char_j = 22,
      Char_k = 23,
      Char_l = 24,
      Char_m = 25,
      Char_n = 26,
      Char_o = 27,
      Char_p = 28,
      Char_q = 29,
      Char_r = 30,
      Char_s = 31,
      Char_t = 32,
      Char_u = 33,
      Char_v = 34,
      Char_w = 35,
      Char_x = 36,
      Char_y = 37,
      Char_z = 38,
      Char__ = 39,
      Char_A = 40,
      Char_B = 41,
      Char_C = 42,
      Char_D = 43,
      Char_E = 44,
      Char_F = 45,
      Char_G = 46,
      Char_H = 47,
      Char_I = 48,
      Char_J = 49,
      Char_K = 50,
      Char_L = 51,
      Char_M = 52,
      Char_N = 53,
      Char_O = 54,
      Char_P = 55,
      Char_Q = 56,
      Char_R = 57,
      Char_S = 58,
      Char_T = 59,
      Char_U = 60,
      Char_V = 61,
      Char_W = 62,
      Char_X = 63,
      Char_Y = 64,
      Char_Z = 65,
      Char_0 = 1,
      Char_1 = 2,
      Char_2 = 3,
      Char_3 = 4,
      Char_4 = 5,
      Char_5 = 6,
      Char_6 = 7,
      Char_7 = 8,
      Char_8 = 9,
      Char_9 = 10,
      Char_AfterASCII = 66,
      Char_Space = 67,
      Char_DoubleQuote = 77,
      Char_SingleQuote = 93,
      Char_Percent = 94,
      Char_VerticalBar = 95,
      Char_Exclamation = 96,
      Char_AtSign = 78,
      Char_BackQuote = 97,
      Char_Tilde = 98,
      Char_Sharp = 79,
      Char_DollarSign = 68,
      Char_Ampersand = 80,
      Char_Caret = 99,
      Char_Colon = 69,
      Char_SemiColon = 81,
      Char_BackSlash = 100,
      Char_LeftBrace = 82,
      Char_RightBrace = 83,
      Char_LeftBracket = 84,
      Char_RightBracket = 85,
      Char_QuestionMark = 101,
      Char_Comma = 86,
      Char_Dot = 70,
      Char_LessThan = 87,
      Char_GreaterThan = 71,
      Char_Plus = 88,
      Char_Minus = 72,
      Char_Slash = 73,
      Char_Star = 89,
      Char_LeftParen = 90,
      Char_RightParen = 91,
      Char_Equal = 92,
      Char_EOF = 74;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9",
                 "HT",
                 "FF",
                 "a",
                 "b",
                 "c",
                 "d",
                 "e",
                 "f",
                 "g",
                 "h",
                 "i",
                 "j",
                 "k",
                 "l",
                 "m",
                 "n",
                 "o",
                 "p",
                 "q",
                 "r",
                 "s",
                 "t",
                 "u",
                 "v",
                 "w",
                 "x",
                 "y",
                 "z",
                 "_",
                 "A",
                 "B",
                 "C",
                 "D",
                 "E",
                 "F",
                 "G",
                 "H",
                 "I",
                 "J",
                 "K",
                 "L",
                 "M",
                 "N",
                 "O",
                 "P",
                 "Q",
                 "R",
                 "S",
                 "T",
                 "U",
                 "V",
                 "W",
                 "X",
                 "Y",
                 "Z",
                 "AfterASCII",
                 "Space",
                 "DollarSign",
                 "Colon",
                 "Dot",
                 "GreaterThan",
                 "Minus",
                 "Slash",
                 "EOF",
                 "LF",
                 "CR",
                 "DoubleQuote",
                 "AtSign",
                 "Sharp",
                 "Ampersand",
                 "SemiColon",
                 "LeftBrace",
                 "RightBrace",
                 "LeftBracket",
                 "RightBracket",
                 "Comma",
                 "LessThan",
                 "Plus",
                 "Star",
                 "LeftParen",
                 "RightParen",
                 "Equal",
                 "SingleQuote",
                 "Percent",
                 "VerticalBar",
                 "Exclamation",
                 "BackQuote",
                 "Tilde",
                 "Caret",
                 "BackSlash",
                 "QuestionMark",
                 "CtlCharNotWS"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
